### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by zdk123** [alexeckert/parallelDist#18]
Any objections to adding this package to [conda-forge](https://conda-forge.org/)?
I'd be happy to [stage a new recipe](https://github.com/conda-forge/staged-recipes), including all the developers as maintainers. 

There is a small overhead for keeping the channel up to date, but a lot of projects are moving to conda for reproducibility.

**Comment by alexeckert** [comment]
Hi @zdk123,

thanks, sounds like a good idea. I think it's sufficient to add me as the maintainer.

**Comment by alexeckert** [comment]
Thanks @zdk123
